### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Isabela-Sales** [Isabela-Sales/components-on-a-grid#1]
@thatkidmadrid

Hello Christian,
Follow my record below. Thank you.

[isabela-sales-020-components-on-a-grid.m4a.zip](https://github.com/Isabela-Sales/components-on-a-grid/files/7196431/isabela-sales-020-components-on-a-grid.m4a.zip)

**Comment by thatkidmadrid** [comment]
Great! I would only read the `grid-template-area` a little differently but we'll go over in class. The way you read it is totally easy to follow, but there's another way that may be even clearer
Describing the grid like `two-by-two grid; first row:  banner, banner; second row: main, main` gives the listener a heads-up for how many columns and rows to anticipate while listening

Also, some of your selectors are very specific - which is totally fine - but you may want to leverage the classes that already exist in some of the components to make writing, referencing, and describing your code simpler

For example, you have a selector for `header h1 {...}` when the h1 already has the class `logo` and can be selected using `.logo {...}`
